exclude: '(\.git/|\.venv/|\.idea/|third_party/|experimental/|bugs/)'
minimum_pre_commit_version: 3.6.0
default_language_version:
  python: "3.13"
  node: "22.20.0"
repos:
  # https://pre-commit.com/hooks.html
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        description: "trims trailing whitespace."
        exclude: ^.*.tsv$
  # nbstripout-fast
  - repo: https://github.com/deshaw/nbstripout-fast.git
    rev: v1.1.1
    hooks:
      - id: nbstripout-fast
  # ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff
        args: ["--output-format", "concise"]
      - id: ruff
        name: ruff-isort
        args: ["--select", "I", "--fix"]
      - id: ruff-format
        args: ["--preview"]
  # pyright
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.406
    hooks:
      - id: pyright
  # markdownlint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args:
          [
            "--disable",
            "MD013", # Line length
            "MD033", # Inline HTML
            "--"  # otherwise files are interpreted as args
          ]
  # shellcheck
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
    - id: shellcheck
      args: ["-x", "--shell=bash", "--color=always", "--format=gcc", "--"]
